<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Mote.Windows</RootNamespace>
    <AssemblyName>Mote.Windows</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.1.0</Version>
    <Product>Mote</Product>
    <Description>Mote for Windows agent.</Description>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Mote.Windows.Tests" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

</Project>
